### PR TITLE
Icon Bounce Option + Winning Icon Option Code (just in case)

### PR DESCRIPTION
**Pull request by DEMOLITIONDON96**
We do be codin'

###### I legit have no idea if the icon bounce shit will work, but for sure, Winning Icon Option is fully functional

### CODE REVIEW

**Comment by Theoyeah** [comment]
If you delete the winning icon option i'll merge the icon bounce

**Comment by DEMOLITIONDON96** [comment]
@Theoyeah Winning Icons Option code works FOR sure, cause this was tested on my engine, but icon bounce stuff is still experimental, and this is the (hopefully) fully functional version of that option, as I also tested this on my engine

**Comment by Theoyeah** [comment]
> @Theoyeah Winning Icons Option code works FOR sure

What i mean is that i don't like the winning icon option, after the rest is ok

**Comment by DEMOLITIONDON96** [comment]
> > @Theoyeah Winning Icons Option code works FOR sure
> 
> What i mean is that i don't like the winning icon option, after the rest is ok

ight, i'll just remove the option to toggle it, but i'm still leaving the code in in case you change your mind, besides, it's set to true anyways, so they'll stay on

**Comment by Theoyeah** [comment]
> > > @Theoyeah Winning Icons Option code works FOR sure
> > 
> > 
> > What i mean is that i don't like the winning icon option, after the rest is ok
> 
> ight, i'll just remove the option to toggle it, but i'm still leaving the code in in case you change your mind, besides, it's set to true anyways, so they'll stay on

Ok

**Comment by DEMOLITIONDON96** [comment]
also, it looks like there's no problems with compiling, that means it's working, now to see if the option itself will actually change the bounce animation for all 3 options (Default was the only option that worked properly at the time when i tested this on my engine btw)

**Comment by Theoyeah** [comment]
Oh wait i thinked that none was the original but it default, and the none is not working properly

**Comment by DEMOLITIONDON96** [comment]
> Oh wait i thinked that none was the original but it default, and the none is not working properly

Is it not bouncing?

**Comment by Theoyeah** [comment]
yes i know

**Comment by DEMOLITIONDON96** [comment]
> yes i know

How does it look like? Cause I don’t have my laptop still and I’m only able to test it on the school computers, but I’m home rn

**Comment by Theoyeah** [comment]
Everythng works fine but the None is broken a bit

**Comment by DEMOLITIONDON96** [comment]
> Everythng works fine but the None is broken a bit

Can you show a ss? I wanna see how it looks in-game

**Comment by Theoyeah** [comment]
the thing is that in "None" the icon starts to zoom like the default does but does not zoom out, leaving a little big icon

**Comment by DEMOLITIONDON96** [comment]
> the thing is that in "None" the icon starts to zoom like the default does but does not zoom out, leaving a little big icon

Big, as in….?

**Comment by DEMOLITIONDON96** [comment]
Are you fucking kidding me, since when does making an if statement that says if the Option is NOT “None” require it to say true or false instead?

**Comment by DEMOLITIONDON96** [comment]
@Theoyeah @Wither362 how’s this code so far?

**Comment by Wither362** [comment]
For me it’s pretty good, but wait until @Theoyeah merge it, because when we merge it he/she can revert the changes

**Comment by Theoyeah** [comment]
Done

**Comment by Wither362** [comment]
> @Theoyeah @Wither362 how’s this code so far?
> 
> Btw, if you plan on merging this if everything works, I would use the “Squash and Merge” option so it looks like one commit instead of multiple commits, cause it’ll end up making it look messy in the commit history

Well, maybe for you if we merged it with the default option it would be messy in the commit history, but for me no, because I did 78 commits in a branch and then I merged it into the main branch! 78 COMMITS! The commit history literally disappeared

**Pull request merged**
