### PR TITLE
Noteskins

### PR DESCRIPTION
**Pull request by Wither362**
Yeah, I’m with it

### CODE REVIEW

**Comment by Wither362** [comment]
@Theoyeah!! ITS COMPILING!

**Comment by Wither362** [comment]
@Theoyeah, is the xml of the circles notes correctly?

**Comment by Theoyeah** [comment]
Yes, it is correct

**Comment by Wither362** [comment]
Woo Ho!

**Comment by Wither362** [comment]
Yeah!

**Comment by Wither362** [comment]
Because try the circles one now, and you will see (I think, I didn’t tested the last version I made) that the circles texture is corrupted

**Comment by Theoyeah** [comment]
> Because try the circles one now, and you will see (I think, I didn’t tested the last version I made) that the circles texture is corrupted

Wait, how did you test it ???? You're on ipad, aren't you ?

**Comment by Wither362** [comment]
> > Because try the circles one now, and you will see (I think, I didn’t tested the last version I made) that the circles texture is corrupted
> 
> Wait, how did you test it ???? You're on ipad, aren't you ?

Yeah, but 10 minutes before I was in the computer, and,


How do you know that I’m in iPad :)?

**Comment by Theoyeah** [comment]
> > > Because try the circles one now, and you will see (I think, I didn’t tested the last version I made) that the circles texture is corrupted
> > 
> > 
> > Wait, how did you test it ???? You're on ipad, aren't you ?
> 
> Yeah, but 10 minutes before I was in the computer, and,
> 
> How do you know that I’m in iPad :)?

Cuz you already told it in one of demo's discussions or smth

**Comment by Wither362** [comment]
> > > > Because try the circles one now, and you will see (I think, I didn’t tested the last version I made) that the circles texture is corrupted
> > > 
> > > 
> > > Wait, how did you test it ???? You're on ipad, aren't you ?
> > 
> > 
> > Yeah, but 10 minutes before I was in the computer, and,
> > How do you know that I’m in iPad :)?
> 
> Cuz you already told it in one of demo's discussions or smth

Oh, ok, thanks for reminding me that

**Comment by Wither362** [comment]
Well, does it work?

**Comment by Theoyeah** [comment]
Im currently working on testing notesphlases

**Comment by Wither362** [comment]
Ok

**Comment by Theoyeah** [comment]
Ok, i gonna test this pr to see if it works

**Comment by Theoyeah** [comment]
Well, there's 2 problem,
1. The noteskin is not changing, only stays on circles
2. The circles xml seems buggy, tho i tried 1 month ago and it worked fine

**Comment by Wither362** [comment]
Ok, AHHHHHHHHHHHHHHHHHHHHDHEJSJJAKHCIJDSJSJNSMXISJSIGDHDHDGHDGHDGHDFHDFHDFHDFHDFHDFHDGHTHRYJDTYJRDYJSRTSRTSRYUSETY!!!!!!!!!!!!!! 🤬!!!!

**Comment by Theoyeah** [comment]
image
Mayo be like:
Cring!

**Comment by Theoyeah** [comment]
oh wait it doesn't work

**Comment by Theoyeah** [comment]
image

**Comment by Theoyeah** [comment]
image

**Comment by Wither362** [comment]
Does it work now?

**Comment by Theoyeah** [comment]
gonna try

**Comment by Wither362** [comment]
And sorry for not answer you in an hour, but I has at

###### school

###### And im still on it!

**Comment by Theoyeah** [comment]
> And sorry for not answer you in an hour, but I has at
> 
> ###### school
> ###### And im still on it!

Don't worry, i was busy

**Comment by Theoyeah** [comment]
So, when you select arrows it works fine, but using circles will switch correclty but not showing properly

**Comment by Wither362** [comment]
> I think the game doesn't switch the xml when we are chosing the circles

Ok, I will see if I can correct that

**Comment by Wither362** [comment]
Does it work @Theoyeah?

**Comment by Theoyeah** [comment]
testing..

**Comment by Wither362** [comment]
Ohh

**Comment by Theoyeah** [comment]
ok

**Pull request closed without merging**
