### PR TITLE
Tweak the FPS Counter for it to look like the Current Base Game one

### PR DESCRIPTION
**Pull request by BeastlyGhost**

### CODE REVIEW

**Comment by Theoyeah** [comment]
Any screenshots ? I would aprreciate it

**Comment by BeastlyGhost** [comment]
> Any screenshots ? I would aprreciate it

it would look like this, I will probably mark this as a draft so I can make an option to disable the RAM counter
image

**Comment by Theoyeah** [comment]
keeep like this

**Comment by BeastlyGhost** [comment]
> keeep like this

sure

**Comment by BeastlyGhost** [comment]
> You can also make an option to disable it (i love options) in case that that works

I will, just gonna compile it really quick

**Comment by Theoyeah** [comment]
> You can also make an option to disable it (i love options) in case that that works

I think it is pretty good just liek this, i don't think we sould make it an option

**Comment by BeastlyGhost** [comment]
in case you guys change your mind I will make a PR for it to have an option to hide the RAM Counter

**Comment by Theoyeah** [comment]
Ok

**Pull request merged**
