### PR TITLE
Note splashes option

### PR DESCRIPTION
**Pull request by Wither362**
Yeah, a note splashes option, do you like it @Theoyeah?

### CODE REVIEW

**Comment by Theoyeah** [comment]
Why Inverted notesplashes, no one would use it, but you can add og noteplashes ill review that

**Comment by Wither362** [comment]
> Why Inverted notesplashes, no one would use it, but you can add og noteplashes ill review that

Well, add the noteSplashes you want, I will do the code, ok? I have here a lot of noteSplashes, so may I bring them here.

**Comment by Wither362** [comment]
Does it works @Theoyeah? Please try the newest version of this

**Comment by DEMOLITIONDON96** [comment]
this would be useful if there were ACTUAL note splash skins, like Forever Engine splash, Andromeda Engine splash, etc.

**Comment by Wither362** [comment]
youre right

**Comment by Wither362** [comment]
Do i merge it @Theoyeah?

**Comment by Theoyeah** [comment]
@Wither362 can you make the game specify that there a notesplashes folder, im not sure of what i need to edit

**Comment by Wither362** [comment]
ok

**Comment by Wither362** [comment]
does it work @Theoyeah?

**Comment by Theoyeah** [comment]
im testing rn

**Comment by Wither362** [comment]
ok

**Comment by Theoyeah** [comment]
Nan, the game says it cant find the images and xml

**Comment by Wither362** [comment]
ok

**Comment by Wither362** [comment]
let me fix it

**Comment by Theoyeah** [comment]
the thing i did was to create a new folder for notesplashes in shared/images 
image

**Comment by Wither362** [comment]
and now?

**Comment by Theoyeah** [comment]
still not.. i tried 2 differents but not..

**Comment by Wither362** [comment]
ok

**Comment by Wither362** [comment]
wait!!

**Comment by Wither362** [comment]
i have an idea!!!!!!!!!!

**Comment by Theoyeah** [comment]
> i have an idea!!!!!!!!!!

Ok ?

**Comment by Wither362** [comment]
and now?

**Comment by Wither362** [comment]
does it work?

**Comment by Theoyeah** [comment]
still n o t

**Comment by Theoyeah** [comment]
still only these things
image

**Comment by Wither362** [comment]
does it work now?

**Comment by Theoyeah** [comment]
Gonna test

**Comment by Wither362** [comment]
Does it work?

**Comment by Theoyeah** [comment]
AAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHH HAXE IS MESSING WITH US

**Comment by Wither362** [comment]
Why?

**Comment by Theoyeah** [comment]
Because it won't work

**Comment by Wither362** [comment]
What does it say?

**Comment by Theoyeah** [comment]
the same thing

**Comment by Wither362** [comment]
But it compile right?

**Comment by Theoyeah** [comment]
yeah

**Comment by Wither362** [comment]
Because sometimes when it says that it also can compile correctly

**Comment by BeastlyGhost** [comment]
have this

noteSplashes

https://cdn.discordapp.com/attachments/929801502829215745/974806762882469918/noteSplashes.xml

offset.set(Std.int(0.3 * width), Std.int(0.3 * height));

**Comment by Wither362** [comment]
> have this
> 
> noteSplashes
> 
> https://cdn.discordapp.com/attachments/929801502829215745/974806762882469918/noteSplashes.xml
> 
> offset.set(Std.int(0.3 * width), Std.int(0.3 * height));

Ok, thanks, I will implement it

**Comment by Wither362** [comment]
Does it work? @Theoyeah?

**Comment by Wither362** [comment]
It works

**Comment by Wither362** [comment]
now im gonna add @BeastlyGhost's ones

**Comment by Wither362** [comment]
@BeastlyGhost, how do I name them? (the notesplashes)

**Comment by Theoyeah** [comment]
Bro, beast's ones are the same as the og

**Comment by Theoyeah** [comment]
so no need to add them

**Comment by Wither362** [comment]
Ok, I will delete them

**Comment by Theoyeah** [comment]
i gonna test this

**Comment by Wither362** [comment]
It works perfectly! (In my computer)

**Comment by Wither362** [comment]
@Theoyeah, does it work?

**Comment by BeastlyGhost** [comment]
I will try to restore some of the notesplashes on Psych's FLA, then I send it to yall

**Comment by Theoyeah** [comment]
The only thing is that the og splashes is not placed correctly when making a marvelous

**Comment by Wither362** [comment]
> I will try to restore some of the notesplashes on Psych's FLA, then I send it to yall

Ok, thanks, also, @BeastlyGhost, I don’t know what @Theoyeah thinks, but I think you would be a excellent *real* contributor, not a pr contributor, what do you think? Do you want to be in the Theoyeah-engine, if @Theoyeah accept it?

**Comment by Wither362** [comment]
> The only thing is that the og splashes is not placed correctly when making a marvelous

Let me fix that ;)

**Pull request merged**
