### PR TITLE
BeatHit CamZoom FIXED!!!!122112

### PR DESCRIPTION
**Pull request by lolbruhfart**
fixed it @Wither362

### CODE REVIEW

**Comment by Theoyeah** [comment]
I'll test it

**Comment by Wither362** [comment]
I like it, but it doesnt stop, let me fix it

**Comment by Wither362** [comment]
Now we need a new song, a tecno/fast song

**Comment by Wither362** [comment]
Im with it: [here](9n72s0k0l00e0bt38a7g0fj07r1i0o2211333T1v1u35f0qwx10l611d08A6F0B0Q05c0Pa660E2bi626T1v1u52f0qwx10v311d08A1F2B4Q00b0Pf519E3b662876T1v1u39f0qwx10l611d08A0F0B0Q38e0Pa610E3b8618626T1v1ue4f0q0w10p5d4aA5F4B0Q0248Pac74E3b8628635T1v1u36f0qww10n51d08A0F0B0Q06e0Pb330E3bi617626T5v1uc9f10j5q00d23HXQRRJJHJAAArq8h0E0T1v1ue5f0q0w10r5d19A5F4BdQ010bPf977E3b862a78T4v1uf0f0q011z6666ji8k8k3jSBKSJJAArriiiiii07JCABrzrrrrrrr00YrkqHrsrrrrjr005zrAqzrjzrrqr1jRjrqGGrrzsrsA099ijrABJJJIAzrrtirqrqjqixzsrAjrqjiqaqqysttAJqjikikrizrHtBJJAzArzrIsRCITKSS099ijrAJS____Qg99habbCAYrDzh00E0T4v1uf0f0q00z6666ji8k8k3jSBKSJJAArriiiiii07JCABrzrrrrrrr00YrkqHrsrrrrjr005zrAqzrjzrrqr1jRjrqGGrrzsrsA099ijrABJJJIAzrrtirqrqjqixzsrAjrqjiqaqqysttAJqjikikrizrHtBJJAzArzrIsRCITKSS099ijrAJS____Qg99habbCAYrDzh00E0b01400000000h4h800000004y8w00000000400000000001000000000040000000000i0000000j4Qgj5m00008klg000000p25vDjFE)

**Comment by lolbruhfart** [comment]
j

**Pull request closed without merging**
