### PR TITLE
Poisoned notes repaired

### PR DESCRIPTION
**Pull request by Wither362**
I’m still with them, so until they work perfectly I will not merge this branch to the engine

### CODE REVIEW

**Comment by Theoyeah** [comment]
Wait, it works ?

**Comment by Wither362** [comment]
Yeah? I didn’t prove it

**Comment by Wither362** [comment]
But if you’re gonna merge it let me do it, because it’s buggy

**Comment by Theoyeah** [comment]
Ok, ima try this later

**Pull request closed without merging**
