### PR TITLE
Die revive option

### PR DESCRIPTION
**Pull request by Wither362**
Instantly revive when death only if option true

### CODE REVIEW

**Comment by Theoyeah** [comment]
Call it Instant Respawn

**Comment by Wither362** [comment]
Ok

**Comment by Wither362** [comment]
I’m gonna merge this ok @Theoyeah?

**Comment by Theoyeah** [comment]
did you test it ?

**Comment by Wither362** [comment]
Nope

**Comment by Theoyeah** [comment]
Then someone need to test it

**Comment by Wither362** [comment]
Ok, I’ll test it later (in about 2 hours)

**Comment by Theoyeah** [comment]
the game quits directly when you die with the option enabled

**Comment by Wither362** [comment]
Oh

**Comment by Theoyeah** [comment]
IT WORKS YEEEESSSSS

**Pull request merged**
