### PR TITLE
NOTESKIS

### PR DESCRIPTION
**Pull request by Theoyeah**

### CODE REVIEW

**Comment by Theoyeah** [comment]
i will test it soon

**Comment by Theoyeah** [comment]
what do you mean by strums ?

**Comment by Wither362** [comment]
> what do you mean by strums ?

The strums are the grey/gray thing, were you press the notes

**Comment by Theoyeah** [comment]
image

**Comment by Wither362** [comment]
> image

Ok, everything is “wrong”

**Comment by BeastlyGhost** [comment]
https://github.com/Theoyeah/Theoyeah-Engine/pull/196 haha

**Pull request closed without merging**
