### PR TITLE
Toggleable RAM Counter

### PR DESCRIPTION
**Pull request by BeastlyGhost**
https://user-images.githubusercontent.com/45212377/177898124-921aa578-d361-4cfb-a5c4-01a8886cbe6e.mp4

### CODE REVIEW

**Comment by MrClogsworthYT** [comment]
approved

**Comment by MrClogsworthYT** [comment]
wait a minute.... FURRY???? unapproved /j

**Comment by Wither362** [comment]
> wait a minute.... FURRY???? unapproved /j

Im furry…

**Comment by MrClogsworthYT** [comment]
> > wait a minute.... FURRY???? unapproved /j
> 
> Im furry…

clearly you didnt see the /j at the end

**Comment by Wither362** [comment]
> > > wait a minute.... FURRY???? unapproved /j
> > 
> > 
> > Im furry…
> 
> clearly you didnt see the /j at the end

I don’t know what "/j" means

**Comment by MrClogsworthYT** [comment]
> > > > wait a minute.... FURRY???? unapproved /j
> > > 
> > > 
> > > Im furry…
> > 
> > 
> > clearly you didnt see the /j at the end
> 
> I don’t know what "/j" means

it means that the statement before was a joke

**Comment by Wither362** [comment]
> > > > > wait a minute.... FURRY???? unapproved /j
> > > > 
> > > > 
> > > > Im furry…
> > > 
> > > 
> > > clearly you didnt see the /j at the end
> > 
> > 
> > I don’t know what "/j" means
> 
> it means that the statement before was a joke

Ok, thanks, I didn’t knew that

**Comment by Theoyeah** [comment]
I coul've have the idea but, eh you already did so..

M e r g i n g  t i m e

**Pull request merged**
