### PR TITLE
Music option

### PR DESCRIPTION
**Pull request by Wither362**
It isn´t finished

### CODE REVIEW

**Comment by Wither362** [comment]
Please add your music

**Comment by Wither362** [comment]
Upload the music sounds

**Comment by Theoyeah** [comment]
i don't have any music

**Comment by Wither362** [comment]
well, in that case....

**Comment by Wither362** [comment]
dont upload anything

**Comment by Wither362** [comment]
and leave it to me

**Comment by DEMOLITIONDON96** [comment]
Don’t put the “.ogg” part in the ClientPrefs of the musicSelected option, cause it’ll actually look for a file named “freakyMenu.ogg.ogg” instead of “freakyMenu.ogg”

**Comment by Wither362** [comment]
ok

**Comment by Wither362** [comment]
you do it or I do it?

**Comment by Theoyeah** [comment]
i will prob not add this for now, we need to focus more in like...
KE 1.8 input ? idk because it starts to make a lot for options

**Comment by Wither362** [comment]
ok

**Pull request closed without merging**
