### PR TITLE
vcr font (YOU CAN PULL NOW

### PR DESCRIPTION
**Pull request by AverageDaveLover65**
this adds like 3 things:
vcr font for the fps thingy
added me to the credits incase you guys forget about me

kay NOW YOU CAN PULL

### CODE REVIEW

**Comment by CrusherNotDrip** [comment]
what if theoyeah or something does pull this 🤔

**Review by MemeHoovy — APPROVED** [review]

**Comment by CrusherNotDrip** [comment]
> what if theoyeah or something does pull this 🤔

this aged well

**Review by Wither362 — COMMENTED** [review]
Ok ok ok, I get it, we’ll credit you

**Comment by Wither362** [comment]
> this adds like 3 things: vcr font for the fps thingy added me to the credits incase you guys forget about me
> 
> kay NOW YOU CAN PULL

Yeah, but… why? Why did you create this pull request?

**Comment by Theoyeah** [comment]
MMhhhh iThink i sould test ta

**Comment by Wither362** [comment]
> MMhhhh iThink i sould test ta

Hey theoyeah! How are you? You didn’t response by a few months ago

**Comment by BeastlyGhost** [comment]
i think this doesn't really match the changes i made to the text fieldthat well, I'd change it to something like this before making any sudden changes to the font
image

**Comment by AverageDaveLover65** [comment]
ok   a yyyyyyyy

**Comment by Theoyeah** [comment]
ok i can try to add it, i'll credit you

**Pull request closed without merging**
