### PR TITLE
Custom achievements!

### PR DESCRIPTION
**Pull request by Wither362**
Isnt proved!!!!!!!!!!!!!!

### CODE REVIEW

**Comment by Theoyeah** [comment]
i gonna test it later

**Comment by Wither362** [comment]
> i gonna test it later

Ok, you already have a custom achievement ok?

**Comment by Theoyeah** [comment]
image
You know that the "week" was the thing that caused the week7 bug in 0.5.2 right ?

**Comment by Theoyeah** [comment]
oh wait, im stupid

**Comment by Theoyeah** [comment]
i still need to test it

**Comment by Wither362** [comment]
IT WORKS

**Comment by Theoyeah** [comment]
don't work /:, it shows correctly but i can't unlock it

**Comment by Theoyeah** [comment]
it works but for weeks the achivement unlocks already when finishing the first song

**Comment by Theoyeah** [comment]
Good news, IT IS FUNKIN APPROVED

**Review by Theoyeah — APPROVED** [review]

**Comment by Theoyeah** [comment]
Just need to remove the test thing we sould be good to go

**Comment by Theoyeah** [comment]
Gonna merge this, WWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEE

**Pull request merged**
