### PR TITLE
Latin Alphabet Support + Item Types

### PR DESCRIPTION
**Pull request by BeastlyGhost**
sample text

### CODE REVIEW

**Comment by BeastlyGhost** [comment]
@Theoyeah check this

**Comment by Theoyeah** [comment]
did you test this, if you did, i merge this i m e d i a t l y

**Comment by BeastlyGhost** [comment]
> did you test this, if you did, i merge this i m e d i a t l y

I tested it months ago, same code, same everything, it works

**Comment by BeastlyGhost** [comment]
for some weird reason it also works with other engines (Forever Engine) for exaample, so it's a plus

**Comment by Theoyeah** [comment]
you won

**Pull request merged**
