### PR TITLE
Combo.png full support

### PR DESCRIPTION
**Pull request by Theoyeah**
Im adding combo.png but with a _twist_
You can adjust the offset like the rating numscore !

(do NOT merge until i tested it to see if it works)

### CODE REVIEW

**Comment by BeastlyGhost** [comment]
would be more efficient to just add two extra numbers to the comboOffset array rather than doing this

public static var comboOffset:Array<Int> = [0, 0, 0, 0]; // current one

public static var comboOffset:Array<Int> = [0, 0, 0, 0, 0, 0]; // new one which should include the values necessary for the combo sprite offset to work

**Comment by Theoyeah** [comment]
The thing im trying to do is to make the combo thing movable like rating and combonums

**Comment by DEMOLITIONDON96** [comment]
How do I revert the latest commit I made?

**Comment by DEMOLITIONDON96** [comment]
> Look at github commit history and right click

I can’t right click, I’m on mobile

**Comment by Theoyeah** [comment]
> > Look at github commit history and right click
> 
> I can’t right click, I’m on mobile, I don’t even have my damn laptop and won’t have it till the end of the god damn school year

I'll help reverting

**Comment by Theoyeah** [comment]
Here's the anoying bug that is blocking me

https://user-images.githubusercontent.com/97792861/167867701-795a5716-2cdb-4712-bcb3-1ede9d3cb39c.mp4

**Comment by Theoyeah** [comment]
It was this commit  where you fixed?
image
Because i just tested it

**Comment by DEMOLITIONDON96** [comment]
> It was this commit where you fixed?
> image
> Because i just tested it

Huh, guess it doesn’t, then again, the way you had the new client pref set up, that’s not gonna work anyways

**Comment by Theoyeah** [comment]
> > It was this commit where you fixed?
> > image
> > Because i just tested it
> 
> Huh, guess it doesn’t, then again, the way you had the new client pref set up, that’s not gonna work anyways

Ok, so from what i understand i need to revert the clientPrefs thing you made ?

**Comment by Theoyeah** [comment]
nan, still the bug

**Comment by Theoyeah** [comment]
@DEMOLITIONDON96 I found out the bug, i just replaced text that sould be replaced, so just need to figure how to fix the selecting glitch

**Comment by Wither362** [comment]
Yeah, take in mind that the value 0 also counts

**Comment by Theoyeah** [comment]
Ok, gonna try it later

**Comment by Theoyeah** [comment]
Still no, there's still the problem

**Comment by Theoyeah** [comment]
@DEMOLITIONDON96 
@DEMOLITIONDON96

**Comment by Theoyeah** [comment]
IVE FOUND OUT THE BUG

**Comment by Theoyeah** [comment]
Capture d’écran 2022-05-13 181418
Quick explanation: It seems that when it is set to true, it will move the combonums or if it is false, it would do the rating
So i need to do a third "choise" so when it is set, it will move the combospr

**Comment by Theoyeah** [comment]
@Wither362 Could you help me finding the solution, i don't have any idea? Like please, i need someone to do the fix

**Comment by Wither362** [comment]
Try to make a string or int one, let me do it

**Comment by Theoyeah** [comment]
> Try to make a string or int one, let me do it

Oh thanks, if you do it correctly, it sould work

**Comment by Wither362** [comment]
Where are those lines?

**Comment by Theoyeah** [comment]
line 278

**Comment by Theoyeah** [comment]
NoteOffsetstate in source/options

**Comment by Wither362** [comment]
ok thanks

**Comment by Wither362** [comment]
this is taking me a while

**Comment by Theoyeah** [comment]
> this is taking me a while

Don't worry, im won't be buzy for 2 days

**Comment by BeastlyGhost** [comment]
looking forward for this btw, but in the meantime, I'd say you guys could keep the combo sprite in the same position as the rating but slightly repositioned so it won't cover up the numbers and the rating itself

**Comment by Theoyeah** [comment]
> looking forward for this btw, but in the meantime, I'd say you guys could keep the combo sprite in the same position as the rating but slightly repositioned so it won't cover up the numbers and the rating itself

Well, the pr serve to make the combo movable, like the rating and combonums

**Comment by Wither362** [comment]
FIXED

**Comment by Wither362** [comment]
I FIXED IT!!!!!!!!!!!!

**Comment by Theoyeah** [comment]
> FIXED

LET'S SEE IF THIS ASS WORKS

**Comment by Theoyeah** [comment]
YES IT IS COMPILING

**Comment by Theoyeah** [comment]
THE MOMENT OF TRUTH

**Comment by BeastlyGhost** [comment]
HOPING FOR IT TO WORK!!!!!!!!!!!!!!!!!!!!

**Comment by Theoyeah** [comment]
It works but...

**Comment by Theoyeah** [comment]
https://user-images.githubusercontent.com/97792861/168336301-adf5b935-2ace-400b-8b0d-03550cd6844b.mp4

But we got a new problem....

**Comment by Wither362** [comment]
Wait what

**Comment by DEMOLITIONDON96** [comment]
Noooooo

**Comment by Theoyeah** [comment]
I really need to make this working, i wished for a long time this

**Comment by Wither362** [comment]
Ok, ok, I will fix that bug, but now I can’t be with the computer, so I can’t really do it now, but I will fix it later

**Comment by Theoyeah** [comment]
> Ok, ok, I will fix that bug, but now I can’t be with the computer, so I can’t really do it now, but I will fix it later

Okie

**Comment by Wither362** [comment]
But now can you help me with putting more flxColors to the flxThings?

**Comment by Theoyeah** [comment]
> But now can you help me with putting more flxColors to the flxThings?

Ima try

**Comment by Wither362** [comment]
I’m with it

**Comment by Wither362** [comment]
ITS COMPILING

**Comment by Wither362** [comment]
There you have 2 versions:
- [the first one (I forgot the null value)](https://github.com/Theoyeah/Theoyeah-Engine/actions/runs/2323825700)
- [the second one](https://github.com/Theoyeah/Theoyeah-Engine/actions/runs/2323827713)

**Comment by Theoyeah** [comment]
> There you have 2 versions, can you prove them? (The two)
> 
> * [the first one (I forgot the null value)](https://github.com/Theoyeah/Theoyeah-Engine/actions/runs/2323825700)
>   
>   * [this is what I did](https://github.com/Theoyeah/Theoyeah-Engine/pull/80/commits/49321a990e4d23b4befd44c634a5ad44796526ab)
> * [the second one](https://github.com/Theoyeah/Theoyeah-Engine/actions/runs/2323827713)
>   
>   * [this is what I did](https://github.com/Theoyeah/Theoyeah-Engine/pull/80/commits/1201d3304cca5010f58f0bd46b194924cce8571d)

Ok, gonna test

**Comment by Theoyeah** [comment]
Ok, so the 2 things does the same result, the rating and combopsr works like expected, but combonums seems to be not working

**Comment by Wither362** [comment]
Ok

**Comment by Theoyeah** [comment]
> Ok

At least we are starting to get good

**Comment by Theoyeah** [comment]
For now i don't see changes

**Comment by Theoyeah** [comment]
compiling time !

**Comment by Theoyeah** [comment]
AHHHHH AH AH AH AAAA 
image

**Comment by Theoyeah** [comment]
haxe like to mess with us
image

**Comment by Wither362** [comment]
> haxe like to mess with us image

yeah

**Comment by Theoyeah** [comment]
arestrdchvhjvh, nv,nv,nv,

**Comment by Theoyeah** [comment]
ok this is starting to get cursed

**Comment by Wither362** [comment]
Please, lets finish it

**Comment by Theoyeah** [comment]
> Please, lets finish it

Yeah, just let us do our thing haxeeeeee

**Comment by Wither362** [comment]
Maybe now its working

**Comment by Wither362** [comment]
Ok, now it isnt giving errors

**Comment by Wither362** [comment]
@Theoyeah ITS COMPILING

**Comment by Theoyeah** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS IIIIIIIIIIIIIIIIIITTTT FUNKIN COMPILE !!!

**Comment by Theoyeah** [comment]
sadly...

**Comment by Theoyeah** [comment]
the comnonums stills not works....

**Comment by Wither362** [comment]
SHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIITTTTTTTTTTTTTTT

**Comment by Theoyeah** [comment]
> SHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIITTTTTTTTTTTTTTT

SSSSSSSSSSSSSSHHHHHHHHHHHHHHHHHHHHHHHHIIIIIIIIIIIITTTTTTTTTTTTTTTTT

**Comment by Wither362** [comment]
Can you compile it with `-debug`?

**Comment by Theoyeah** [comment]
> Can you compile it with `-debug`?

Ok, it will some time but ok

**Comment by Theoyeah** [comment]
Done compiling with -debug

**Comment by Wither362** [comment]
try it and see what it does

**Comment by Theoyeah** [comment]
> 

Well, the log says nothing, and no change with the bug

**Comment by Theoyeah** [comment]
I merged the main branch into this pr to see if it fixed

**Comment by Wither362** [comment]
Ok

**Comment by Theoyeah** [comment]
still no change, same bug

**Comment by Theoyeah** [comment]
i feel sad, i would like so much to make it working, we are so close

**Comment by Wither362** [comment]
You’re right

**Comment by Wither362** [comment]
I will try to fix it ok? Don’t close this pr

**Comment by Theoyeah** [comment]
thx

**Comment by Theoyeah** [comment]
Oh god

**Comment by Theoyeah** [comment]
because i won't abondon this

**Comment by Wither362** [comment]
Ok

**Comment by Wither362** [comment]
I will see the freaking bug

**Comment by Theoyeah** [comment]
As far i know, this issue have to be with these lines:
image
and this code
```
			if (FlxG.mouse.justPressed)
			{
				function omg(first:Dynamic):Bool { //i dont want to write all the code again and again
					if(startMousePos.x - first.x >= 0 && startMousePos.x - first.x <= first.width &&
						startMousePos.y - first.y >= 0 && startMousePos.y - first.y <= first.height) {
						return true;
					} else {
						return false;
					}
				}
				holdingObjectType = null;
				FlxG.mouse.getScreenPosition(camHUD, startMousePos);
				if (omg(comboNums))
				{
					holdingObjectType = 2; //this was true
					startComboOffset.x = ClientPrefs.comboOffset[2]; //x
					startComboOffset.y = ClientPrefs.comboOffset[3]; //y
					trace("you're holding comboNums: $holdingObjectType");
				}
				else if (omg(rating))
				{
					holdingObjectType = 0; //this was false
					startComboOffset.x = ClientPrefs.comboOffset[0]; //x
					startComboOffset.y = ClientPrefs.comboOffset[1]; //y
					trace("you're holding rating: $holdingObjectType");
				}
				else if (omg(combosprshit))
				{
					holdingObjectType = 4;
					startComboOffset.x = ClientPrefs.comboOffset[4]; //x
					startComboOffset.y = ClientPrefs.comboOffset[5]; //y
					trace("you're holding combo: $holdingObjectType");
				}
			}
			if(FlxG.mouse.justReleased) {
				holdingObjectType = null;
				trace("you're holding anything: $holdingObjectType");
			}

			if(holdingObjectType != null)
			{
				if(FlxG.mouse.justMoved)
				{
					var mousePos:FlxPoint = FlxG.mouse.getScreenPosition(camHUD);
					/*before:
					//var addNum:Int = holdingObjectType? 2 : 0;
					//now:*/

					if(holdingObjectType >= 0) {
						ClientPrefs.comboOffset[holdingObjectType + 0] = Math.round((mousePos.x - startMousePos.x) + startComboOffset.x);
						ClientPrefs.comboOffset[holdingObjectType + 1] = -Math.round((mousePos.y - startMousePos.y) - startComboOffset.y);
						repositionCombo();
					}
				}
			}

```

**Comment by Theoyeah** [comment]
ohhhh ima test that

**Comment by Theoyeah** [comment]
still not...
Haxe is really giving no mercy

**Comment by Theoyeah** [comment]
im filled with dertermination

**Comment by Wither362** [comment]
> im filled with dertermination

IM TOO

**Comment by Wither362** [comment]
I’m gonna delete this system and create another ok? But don’t close this branch neither this pull request, I will do it here

**Comment by Theoyeah** [comment]
ok

**Comment by Wither362** [comment]
Please work

**Comment by Wither362** [comment]
Does it work?

**Comment by Wither362** [comment]
@Theoyeah ?

**Comment by Theoyeah** [comment]
oh, sorry i was playing undertale so i didn't get any notification

**Comment by Theoyeah** [comment]
i gonna test it

**Comment by Theoyeah** [comment]
No, still the bug

**Comment by Wither362** [comment]
why? only why?

**Comment by Theoyeah** [comment]
> why? only why?

?????
Tho, from the logs, the game don't even think im cliking it

**Comment by Theoyeah** [comment]
wait, i gonna try something

**Comment by Theoyeah** [comment]
nvm

**Comment by Wither362** [comment]
> nvm

What does that mean?

**Comment by Theoyeah** [comment]
> > nvm
> 
> What does that mean?

It means "nevermind"

**Comment by Wither362** [comment]
> > > nvm
> > 
> > 
> > What does that mean?
> 
> It means "nevermind"

Oh thanks

**Comment by Wither362** [comment]
I think the problem is here:

https://github.com/Theoyeah/Theoyeah-Engine/blob/59c5d303ccbaec266f66ed75bc51c3ec1c460476/source/options/NoteOffsetState.hx

**Comment by Theoyeah** [comment]
????

**Comment by Theoyeah** [comment]
we already know what file causes the bug for a long time

**Comment by Wither362** [comment]
Wait

**Comment by Wither362** [comment]
> we already know what file causes the bug for a long time

Maybe is _NOT THAT FILE_

**Comment by Theoyeah** [comment]
> > we already know what file causes the bug for a long time
> 
> Maybe is _NOT THAT FILE_

BunniesWhatGIF
# W h a t ?

**Comment by Wither362** [comment]
> > > we already know what file causes the bug for a long time
> > 
> > 
> > Maybe is _NOT THAT FILE_
> 
> BunniesWhatGIF [ ](https://user-images.githubusercontent.com/97792861/173193546-bba13461-9d62-4bc6-9ac6-dfbab318776e.gif) BunniesWhatGIF [ ](https://user-images.githubusercontent.com/97792861/173193546-bba13461-9d62-4bc6-9ac6-dfbab318776e.gif)
> 
> # W h a t ?

Think about it, maybe NoteOffsetState.hx uses a function from other file, and that file only admits dragging 2 sprites!

**Comment by Theoyeah** [comment]
then that means we need to find that file... ?

**Comment by Theoyeah** [comment]
um, you made all the things non-movable

**Comment by Wither362** [comment]
> um, you made all the things non-movable

What do you mean

**Comment by Wither362** [comment]
Sorry

**Comment by Wither362** [comment]
I will return it back

**Comment by Theoyeah** [comment]
ok

**Comment by Theoyeah** [comment]
ohhhhh

**Comment by Theoyeah** [comment]
wait i gonna compile to test if it works

**Comment by Theoyeah** [comment]
yeah it works but we still have comboNums not letting me moving

**Comment by Wither362** [comment]
Im going to try to repair this shit ok @Theoyeah?

**Comment by Theoyeah** [comment]
ok

**Comment by BeastlyGhost** [comment]
yall need sum help?

Uploading 8mb.video-lVK-pQG8l9oS.mp4…

**Comment by BeastlyGhost** [comment]
yall need sum help?

https://user-images.githubusercontent.com/45212377/176199854-b2c6c3b5-54c6-463b-bfe5-8e1b51d4ef56.mp4

**Comment by Theoyeah** [comment]
> yall need sum help?
> 
>  8mb.video-lVK-pQG8l9oS.mp4

WWWWWWWWWWWAAAAAAAIIIIITTT WWWHHHHHHHAT ??????????????????????!!!!!!!!!!

**Comment by Wither362** [comment]
> yall need sum help?
> 
>  8mb.video-lVK-pQG8l9oS.mp4

# HOW THE F*** DID YOU DO THAT!?!?

**Comment by BeastlyGhost** [comment]
https://github.com/Theoyeah/Theoyeah-Engine/pull/205

**Pull request closed without merging**
