### PR TITLE
Cheating allowed repaired

### PR DESCRIPTION
**Pull request by Wither362**
I have deleted the botplay, the practice, the health gain, the scroll speed, and that, but i will repaired

### CODE REVIEW

**Comment by Theoyeah** [comment]
gameplay changers sould be not allowed in story mode even when cheating is allowed

**Comment by Wither362** [comment]
Ok, i will fix that

**Comment by Wither362** [comment]
Ok, now it’s ready

**Comment by Wither362** [comment]
@Theoyeah, should I merge this?

**Comment by Theoyeah** [comment]
i gonna see it later

**Comment by Wither362** [comment]
> i gonna see it later

Ok

**Pull request merged**
