### PR TITLE
New things for charting

### PR DESCRIPTION
**Pull request by Wither362**

### CODE REVIEW

**Comment by Theoyeah** [comment]
What it adds ?

**Comment by Wither362** [comment]
It adds that you can load the chart at a specific difficulty, if you didn’t say what difficulty, it will be the default

**Comment by Theoyeah** [comment]
Well, how do we choose the specific difficulty ?

**Comment by Wither362** [comment]
See the function

**Comment by Wither362** [comment]
Loadsong, there is the thing

**Comment by Theoyeah** [comment]
Sorry, but in chary editor you can't but an -

**Comment by Wither362** [comment]
Yeah, but for coding is great, like the flxThings, like this: 
```haxe
if(FlxG.keys.justPressedY) {
        ChartingState.loadSong(“die”, “expert”);
}
```
Or something like that

**Pull request closed without merging**
