### PR TITLE
Noteskins

### PR DESCRIPTION
**Pull request by Wither362**
I’m with the noteskins

### CODE REVIEW

**Comment by Wither362** [comment]
Please @Theoyeah, the files

**Comment by Theoyeah** [comment]
what files ??????

**Comment by Wither362** [comment]
The noteskins, can you put them in a noteskin folder please?

**Comment by Theoyeah** [comment]
ok

**Comment by Theoyeah** [comment]
done

**Comment by Wither362** [comment]
I don’t see it

**Comment by Wither362** [comment]
I’m in the iPad so I can’t do it myself, but can you please put [this file](https://github.com/Theoyeah/Theoyeah-Engine/blob/Noteskin-works/assets/shared/images/NOTE_assets-Circles.png), [this other file](https://github.com/Theoyeah/Theoyeah-Engine/blob/Noteskin-works/assets/shared/images/NOTE_assets-Circles.xml), [this other file](https://github.com/Theoyeah/Theoyeah-Engine/blob/Noteskin-works/assets/shared/images/NOTE_assets.png), [and this file](https://github.com/Theoyeah/Theoyeah-Engine/blob/Noteskin-works/assets/shared/images/NOTE_assets.xml) into a new folder called `noteSkins` in `assets/shared/images/`?

**Comment by Wither362** [comment]
Nothing nothing

**Comment by Wither362** [comment]
It’s ready, thanks

**Comment by Wither362** [comment]
My iPad wasn’t loading

**Comment by Wither362** [comment]
I need help, it gives me an error, but I don’t know how to fix it, can someone please help me? @Theoyeah?

**Comment by Wither362** [comment]
@Theoyeah, does it work?

**Comment by Theoyeah** [comment]
testing

**Comment by Theoyeah** [comment]
OK wtf happened to my pc with the engine ????:


```

Faulting application name TheoyeahEngine.exe, version: 0.0.0.0, timestamp: 0x628f4586
Faulting module name: TheoyeahEngine.exe, version: 0.0.0.0, timestamp: 0x628f4586
Exception code: 0xc0000005
Error offset: 0x000000000022b2a2
Faulting Process ID: 0x3ca4
Faulting application start time: 0x01d870e1757845b0
Faulting application path: F:\Jeux\FRIDAY NIGHT FUNKIN'\Theoyeah-Engine\export\release\windows\bin\TheoyeahEngine.exe
Faulting module path: F:\Jeux\FRIDAY NIGHT FUNKIN'\Theoyeah-Engine\export\release\windows\bin\TheoyeahEngine.exe
Report ID: 31755d33-30ea-4953-9820-24e848e3f344
Faulting package full name:
Application ID relative to the failing package:
```

I found that in the
event viewer


I gonna restart my pc

**Comment by Theoyeah** [comment]
OK WTF I JUST RESTARTED
image

**Comment by Theoyeah** [comment]
i gonna try a clean compile to see if it works

**Comment by Theoyeah** [comment]
the sus thing is that i was actuallly testing demolition Engine, it compiled and starting correctly

**Comment by Wither362** [comment]
Ok, compile it again

**Comment by Wither362** [comment]
> OK wtf happened to my pc with the engine ????:
> 
> ```
> 
> Faulting application name TheoyeahEngine.exe, version: 0.0.0.0, timestamp: 0x628f4586
> Faulting module name: TheoyeahEngine.exe, version: 0.0.0.0, timestamp: 0x628f4586
> Exception code: 0xc0000005
> Error offset: 0x000000000022b2a2
> Faulting Process ID: 0x3ca4
> Faulting application start time: 0x01d870e1757845b0
> Faulting application path: F:\Jeux\FRIDAY NIGHT FUNKIN'\Theoyeah-Engine\export\release\windows\bin\TheoyeahEngine.exe
> Faulting module path: F:\Jeux\FRIDAY NIGHT FUNKIN'\Theoyeah-Engine\export\release\windows\bin\TheoyeahEngine.exe
> Report ID: 31755d33-30ea-4953-9820-24e848e3f344
> Faulting package full name:
> Application ID relative to the failing package:
> ```
> 
> I found that in the event viewer
> 
> I gonna restart my pc

That looks like a problem of the compiling, not the code, can you try to compile it again?

**Comment by Theoyeah** [comment]
Ok, your code have a problem, i can use my engine when in the main branch but not this branch

**Comment by Wither362** [comment]
> Ok, your code have a problem, i can use my engine when in the main branch but not this branch

Wtf

**Comment by Wither362** [comment]
Now I understand it,

**Comment by Wither362** [comment]
> The application ID (IDentification) is the same as SOMETHING of your computer, like another application or package, or something hard coded inside the computer, that’s why you can’t compile it, but can you download the newest version and try it please?

I didn’t say anything, it happens the same with my computer

**Comment by Theoyeah** [comment]
yeah, impossible to test

**Comment by Theoyeah** [comment]
do you know anything that can fix it ?

**Comment by Wither362** [comment]
> do you know anything that can fix it ?

Nope

**Comment by Theoyeah** [comment]
i think the only way to fix it is make a new pr

**Comment by Wither362** [comment]
> i think the only way to fix it is make a new pr

Yeah, can you create it? Im mean the pr. I will write the code and do it when I get to my house ok?

**Comment by Theoyeah** [comment]
sure, i'll delete this branch and make a new one

**Pull request closed without merging**
