### PR TITLE
Noteskin System

### PR DESCRIPTION
**Pull request by BeastlyGhost**
image

### CODE REVIEW

**Comment by BeastlyGhost** [comment]
don't know why tf my latin stuff also did go through, github is weird

**Comment by Theoyeah** [comment]
oh god, i need to test that

**Comment by Theoyeah** [comment]
# If this actually works, i'll become insane

**Comment by BeastlyGhost** [comment]
haha it does work, I just made a few mistakes while pushing everything to github which kinda sucks

**Comment by Theoyeah** [comment]
# OH MY GGGOOOODDDDD, IT WORKS SLMIHNDJSNCND.N?.CNS

**Pull request merged**
