### PR TITLE
Flx things

### PR DESCRIPTION
**Pull request by Wither362**
I’m creating functions for creating flx object easier

### CODE REVIEW

**Comment by DEMOLITIONDON96** [comment]
This is interesting, so, this is like, making Lua Scripts, but in Haxe?

**Comment by Wither362** [comment]
Yeah? I created this for not having to write the code again and again, but that’s a good idea!

**Comment by DEMOLITIONDON96** [comment]
Gonna add imports to a bunch of packages, for more functions later on

**Comment by Theoyeah** [comment]
Hello guys, sorry for not responsing, i was in college but the wi-fi got a serious problem, but seems cool

**Comment by Theoyeah** [comment]
> what the hell you’ve been doing
Well, i did nothing as i wi-fi died

**Comment by DEMOLITIONDON96** [comment]
F2FFAED4-730A-47C1-A0BD-D2073964CD0B

Adding more packages

**Comment by Wither362** [comment]
Looks nice

**Comment by Wither362** [comment]
You can also do `import openFL.*` to import the entire openFL

**Comment by Wither362** [comment]
Omg

**Comment by DEMOLITIONDON96** [comment]
> Omg

I am very pro. /j
8BDAB7CE-A0A8-433A-8DC4-9113D5CBB66F

**Comment by DEMOLITIONDON96** [comment]
This is fucking epic, I wonder if we can find a way to make this functional as an alternate to Lua for scripting, though, it might be more work, since we gotta implement it to the code in literally every state

**Comment by Wither362** [comment]
Yeah, you’re right, but this is the question: who’s gonna look at the codes for doing that?

**Comment by DEMOLITIONDON96** [comment]
> Yeah, you’re right, but this is the question: who’s gonna look at the codes for doing that?

Well, we can always look at FunkinLua and the states each function go to, and try replicating that, but for FlxScripts

**Comment by Wither362** [comment]
Ok, I will take a look

**Comment by DEMOLITIONDON96** [comment]
# bro, if we actually manage to pull this off, this way of scripting will be so much more powerful than Lua scripting, since you can do much more than you can with Lua atm already, and the actual game is already coded in Haxe

**Comment by DEMOLITIONDON96** [comment]
I promise ya, I will help ya as much as I can when I get my laptop back, cause I really want to make this a possibility now, besides, I don’t like Lua anyways

**Comment by Wither362** [comment]
Ok, should I continue with it?

**Comment by Wither362** [comment]
And also, can you write here a list of ideas for me to do those ideas?

**Comment by Theoyeah** [comment]
seems interesting, i'll give a try

**Pull request closed without merging**
